// CUANTO DEBE EL USUARIO EN SESIÓN EN TOTAL ENTRE TODOS LOS PROYECTOS
// CUANTO DEBE UN USUARIO (pod id) EN TOTAL EN UN PROYECTO
// CUANTO LE DEBE UN USUARIO (por id) A OTRO USUARIO (por id) EN UN PROYECTO (por id)